Repository flyingsaucerproject/flyingsaucer, pull requests merged in 2023-09, with the labels that each got.

#173 Make VerifyGlyphExists compile using IntelliJ
  flying-saucer-core/pom.xml
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/style/derived/BorderPropertySet.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/FontUtil.java
  flying-saucer-examples/src/main/java/VerifyGlyphExists.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextFontResolver.java
  pom.xml
Labels: refactoring

#198 fix IDEA warnings "Unnecessary boxing"
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/constants/CSSName.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/constants/ValueConstants.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/parser/property/Conversions.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/BoxBuilder.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/LayoutContext.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/AbstractButtonField.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/FormField.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/ImageField.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/SelectField.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/TextAreaField.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/TextField.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/DOMInspector.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/HTMLTest.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/JDKXRLogger.java
  flying-saucer-core/src/test/java/eeze/Eeze.java
  flying-saucer-examples/src/main/java/org/xhtmlrenderer/demo/browser/BrowserActions.java
  flying-saucer-examples/src/main/java/org/xhtmlrenderer/demo/browser/BrowserMenuBar.java
  flying-saucer-examples/src/main/java/org/xhtmlrenderer/demo/browser/ScaleFactor.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/simple/PDFRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/simple/PDFRenderer.java
Labels: refactoring

#204 #184 extract loading CJK fonts by default
  flying-saucer-core/src/main/java/org/xhtmlrenderer/context/AWTFontResolver.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/extend/FontResolver.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextFontResolver.java
  flying-saucer-pdf/pom.xml
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/CJKFontResolver.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/FontDescription.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/FontFamily.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextFSFont.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextFontResolver.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextOutputDevice.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextTextRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/TrueTypeUtil.java
Labels: refactoring, performance

#206 do not expose JSR 302 as transitive dependency to other projects
  pom.xml
Labels: dependencies

#214 fix IDEA inspection "Field may be 'final'"
  .idea/inspectionProfiles/Project_Default.xml
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/style/derived/ColorValue.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/style/derived/FunctionValue.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/style/derived/LengthValue.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/style/derived/NumberValue.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/PersistentBFC.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/breaker/BreakAnywhereLineBreakStrategy.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/breaker/ListBreakPointsProvider.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/breaker/UrlAwareLineBreakIterator.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/render/LineMetricsAdapter.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/render/TextDecoration.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/resource/AbstractResource.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/resource/ImageResource.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/simple/extend/form/SizeLimitedDocument.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/AWTFSFont.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/EmptyReplacedElement.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/Java2DFontContext.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/Java2DOutputDevice.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/ScaleChangeEvent.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/SwingReplacedElement.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/PermutationGenerator.java
  flying-saucer-examples/src/main/java/org/xhtmlrenderer/demo/browser/actions/FontSizeAction.java
  flying-saucer-fop/src/main/java/org/xhtmlrenderer/fop/nbsp/NonBreakPointsEnhancer.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextFSFont.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextFSImage.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextImageElement.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextTextRenderer.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/PDFAsImage.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/TextFormField.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextFSImage.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextImageElement.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextTextRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/PDFAsImage.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/TextFormField.java
  flying-saucer-swt-examples/src/main/java/org/xhtmlrenderer/demo/browser/swt/BrowserStatus.java
  flying-saucer-swt-examples/src/main/java/org/xhtmlrenderer/demo/browser/swt/actions/AbstractAction.java
  flying-saucer-swt-examples/src/main/java/org/xhtmlrenderer/demo/browser/swt/actions/DemoAction.java
  flying-saucer-swt-examples/src/main/java/org/xhtmlrenderer/demo/browser/swt/actions/LoadAction.java
  flying-saucer-swt/src/main/java/org/xhtmlrenderer/simple/xhtml/swt/SWTXhtmlControl.java
  flying-saucer-swt/src/main/java/org/xhtmlrenderer/swt/FormControlReplacementElement.java
  flying-saucer-swt/src/main/java/org/xhtmlrenderer/swt/ImageReplacedElement.java
Labels: refactoring
