Repository flyingsaucerproject/flyingsaucer, pull requests merged in 2023-12, with the labels that each got.

#241 #216 implement loading resources from classpath
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/NaiveUserAgent.java
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/ConcurrentPdfGenerationTest.java
  flying-saucer-examples/src/test/resources/sample.html
  flying-saucer-examples/src/test/resources/styles/sample.css
Labels: feature

#244 upgrade from JUnit 3/4 to JUnit 5
  flying-saucer-core/pom.xml
  flying-saucer-core/src/test/java/org/xhtmlrenderer/css/parser/ParserTest.java
  flying-saucer-core/src/test/java/org/xhtmlrenderer/layout/breaker/UrlAwareLineBreakIteratorTest.java
  flying-saucer-core/src/test/java/org/xhtmlrenderer/simple/Graphics2DRendererTest.java
  flying-saucer-core/src/test/java/org/xhtmlrenderer/swing/NaiveUserAgentTest.java
  flying-saucer-core/src/test/java/org/xhtmlrenderer/util/ConfigurationTest.java
  flying-saucer-examples/pom.xml
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/ConcurrentPdfGenerationTest.java
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/PDFRenderTest.java
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/PDFRenderToMultiplePagesTest.java
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/SimpleHtmlTest.java
  flying-saucer-fop/pom.xml
  flying-saucer-fop/src/test/java/org/xhtmlrenderer/fop/PDFHyphenationTest.java
  flying-saucer-fop/src/test/java/org/xhtmlrenderer/fop/nbsp/NonBreakPointsEnhancerTest.java
  flying-saucer-fop/src/test/java/org/xhtmlrenderer/fop/nbsp/NonBreakPointsLoaderImplTest.java
  flying-saucer-fop/src/test/java/org/xhtmlrenderer/fop/nbsp/NonBreakPointsTest.java
  flying-saucer-log4j/pom.xml
  flying-saucer-pdf-itext5/pom.xml
  flying-saucer-pdf/pom.xml
  flying-saucer-pdf/src/test/java/org/xhtmlrenderer/pdf/DocumentSplitterTest.java
  flying-saucer-pdf/src/test/java/org/xhtmlrenderer/pdf/borderradius/BorderRadiusNonRegressionTest.java
  flying-saucer-pdf/src/test/java/org/xhtmlrenderer/pdf/bug/EndlessLoopTest.java
  flying-saucer-pdf/src/test/java/org/xhtmlrenderer/pdf/bug/OutlineGenerationIssueTest.java
  flying-saucer-swt-examples/pom.xml
  flying-saucer-swt/pom.xml
  pom.xml
Labels: dependencies, refactoring

#246 Added page size B5
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/parser/property/PageSize.java
Labels: feature

#245 Replace iText 2.x by OpenPDF
  CHANGELOG.md
  LICENSE
  README.md
  doc/guide/include/common-defines.inc
  doc/guide/users-guide-r7.xil
  doc/guide/users-guide-r8.xil
  flying-saucer-examples/pom.xml
  flying-saucer-examples/src/main/java/FontGlyphTableRender.java
  flying-saucer-examples/src/main/java/org/xhtmlrenderer/demo/browser/BrowserActions.java
  flying-saucer-fop/pom.xml
  flying-saucer-pdf-itext5/pom.xml
  flying-saucer-pdf/pom.xml
  lib/iText-2.1.7.jar
  pom.xml
  www/dir.xilconfig
  www/faq.html
  www/faq.xil
  www/include/common-defines.inc
Labels: dependencies, refactoring, java

#247 add few overloaded constructors to ITextRenderer
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/IOUtil.java
  flying-saucer-examples/src/main/java/PDFRender.java
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/PDFRenderTest.java
  flying-saucer-fop/src/test/java/org/xhtmlrenderer/fop/PDFHyphenationTest.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextFontResolver.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
  flying-saucer-pdf-itext5/src/main/java/org/xhtmlrenderer/pdf/ITextUserAgent.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextFontResolver.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextReplacedElementFactory.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextUserAgent.java
  flying-saucer-pdf/src/test/resources/org/xhtmlrenderer/pdf/borderradius/borderRadiusWithBorderWidthZero.html
Labels: refactoring, feature
