Repository flyingsaucerproject/flyingsaucer, pull requests merged in 2024-10, with the labels that each got.

#410 #403 don't embed slf4j-api in flying-saucer-pdf-osgi
  pom.xml
Labels: dependencies

#417 #412 [cleanup] Remove unused java sources from "src" folder
  .cvsignore
  .hgignore
  bin/add-temp-cp.bat
  bin/boxer.bat
  bin/eeze.bat
  bin/find-missing-license.sh
  bin/jsrc.bat
  bin/www-xilize.sh
  doc/.cvsignore
  doc/guide/todo-documentation.txt
  doc/guide/users-guide-r7.xil
  doc/guide/users-guide-r8.xil
  flying-saucer-examples/nomaven/svg/.cvsignore
  flying-saucer-examples/samples/.cvsignore
  notes/changes.txt
  src/experimental/java/org/xhtmlrenderer/experimental/ImageLoader.java
  src/experimental/java/org/xhtmlrenderer/experimental/WorkQueue.java
  src/java/utilities/Thumbnails.java
  src/packaging/aboutbox/aboutbox_demo.jnlp
  src/packaging/browser/browser_demo.jnlp
  temp/flyingsaucer.png
  temp/img_scale.htm
  test/.cvsignore
  tests/gecko/gecko-sample.zip
  tests/regress/.cvsignore
  tests/regress/snapshots/regress-output-R8.zip
  www/demos.xil
  www/index.html
  www/index.xil
  www/sig/flyingsaucer-R8-src.zip.asc.txt
  www/sig/flyingsaucer-R8-src.zip.md5.txt
  www/sig/flyingsaucer-R8.zip.asc.txt
  www/sig/flyingsaucer-R8.zip.md5.txt
Labels: refactoring

#420 #411 fix center li items with margin or padding
  flying-saucer-core/src/main/java/org/xhtmlrenderer/render/ListItemPainter.java
  flying-saucer-examples/src/main/resources/demos/list.xhtml
Labels: bug

#419 #409 refactor XRLogger
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/JDKXRLogger.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/XRLog.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/util/XRLogger.java
  flying-saucer-log4j/src/main/java/org/xhtmlrenderer/log4j/Log4JXRLogger.java
  flying-saucer-log4j/src/main/java/org/xhtmlrenderer/log4j/package-info.java
Labels: refactoring

#428 Fix pdf formatting
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/SharedContext.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/swing/Java2DRenderer.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
  flying-saucer-swt/src/main/java/org/xhtmlrenderer/swt/PrinterRenderer.java
Labels: bug

#427 #425 restore method ITestRenderer.getWriter()
  flying-saucer-examples/src/test/java/org/xhtmlrenderer/pdf/PDFRenderToMultiplePagesTest.java
  flying-saucer-pdf/src/main/java/org/xhtmlrenderer/pdf/ITextRenderer.java
Labels: bug

#432 Fix borders
  flying-saucer-core/src/main/java/org/xhtmlrenderer/css/style/derived/BorderPropertySet.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/newtable/CollapsedBorderValue.java
Labels: bug

#433 Fix NPE in blocking formatting contexts
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/LayoutContext.java
  flying-saucer-core/src/main/java/org/xhtmlrenderer/layout/LayoutState.java
Labels: bug
